### ISSUE TITLE
Syntax highlighting doesn't works

### ISSUE THREAD

**Issue by MarlBurroW** [addisonhall/ahdesign.antlers#10]
I've the extension installed on vscode.
On `.antlers.html` files, the format detected is `HTML (Statamic Antlers)` as expected.
But the syntax highlighting still not works.
And as you can see on the screenshot, I've weird javascript syntax related errors in the Problems tab (but it's probably not related to this current issue)

![image](https://user-images.githubusercontent.com/3024430/175793448-cea11b62-138a-4a6c-8f89-273458747d3c.png)

Something is probably miss-configured on my IDE. Do you know where I can search something wrong ?

**Comment by MarlBurroW** [comment]
Ok the javascript errors are here because I've a <script> tag in the page with antlers directives inside.
So not related with the syntax highlighting issue. Pay no attention to it

**Comment by addisonhall** [comment]
No worries, @MarlBurroW. I haven't had the time to give this the love it needs, so I highly recommend this version:

https://antlers.dev/

It looks much more useful than what I built! ;-)
