### ISSUE TITLE
HTML Intellisense and Antlers?

### ISSUE THREAD

**Issue by bgarrant** [addisonhall/ahdesign.antlers#3]
I noticed that HTML Intellisense does not work once you install Antlers. Is there any way to make it work? If you type `<div class` you will notice that no Intellisense or Autocomplete will work. Can you get this working?

There must be a way as I have seen other plugins do it. 

Thanks

**Comment by addisonhall** [comment]
I'm seeing some basic autocomplete already... For example, if I type:

`<d`

I get:

```
date
days_ago
div
```

That may be due to another extension, but I'm not certain. Is that not what you get?

**Comment by bgarrant** [comment]
I am just getting the text based suggestions.  Nothing with the wrench icon.  Are you getting the wrench icon next to the suggestions?

![screen shot 2018-01-08 at 11 49 58 am](https://user-images.githubusercontent.com/2436728/34681506-1572808c-f46a-11e7-8da7-db4f6c343542.png)

**Comment by bgarrant** [comment]
Here is diff when HTML Intellisense is working.  Just change your page language to HTML

![screen shot 2018-01-08 at 11 55 20 am](https://user-images.githubusercontent.com/2436728/34681781-e28c721c-f46a-11e7-8b3d-30c5372ebe9d.png)

**Comment by addisonhall** [comment]
Ah, I see. I'll try to work this in to the next release.

**Comment by bgarrant** [comment]
Thanks so much. I was looking for a workaround but was unable to find one.  There is a way you can include the HTML language in with the extension as I know some others do it.  I think this one has it: https://marketplace.visualstudio.com/items?itemName=mblode.twig-language

**Comment by addisonhall** [comment]
This should be working now in 0.0.4. Be sure to check out the README as things are a little different. Thanks!

**Comment by bgarrant** [comment]
Thanks.  I will try it out asap.

**Comment by bgarrant** [comment]
Seems to work great!

**Comment by addisonhall** [comment]
Good deal. Glad to hear it.
