### ISSUE TITLE
Antlers comment don't work

### ISSUE THREAD

**Issue by jimblue** [addisonhall/ahdesign.antlers#5]
Hello @addisonhall ,

First thanks for this very nice VSCode extension I use it everyday ! 😄 

I've only notice a little issue when commenting a line.
It's actually commenting using HTML comment not Antlers.

comments should look like this:
```
{{# {{ collection:photos }} #}}
```

but they are rendered like so:
```
<!-- {{ collection:photos }} -->
```

Can you confirm that issue ?

Thanks

**Comment by addisonhall** [comment]
@jimblue I'm glad you find this useful! I think this got goofed up in this commit where I tried to enable HTML intellisense:

https://github.com/addisonhall/ahdesign.antlers/commit/f30b52a73aaecc0318b551267ea3f7f7873e33c8

I'm afraid I haven't had the time to really dig into a good solution, but it looks as though I'd have to write and include my own HTML grammar to have the best of both worlds.

**Comment by sunscreem** [comment]
Hey @addisonhall sorry to bug you on this, just wondered if you've any plans on this one?

**Comment by addisonhall** [comment]
> Hey @addisonhall sorry to bug you on this, just wondered if you've any plans on this one?

I had forgotten to check the issues, but I think the latest version fixes this... So now if you're editing with Antlers, comments will default to Antlers comments instead of HTML. I'll close this if someone can confirm that this is the case.

**Comment by sunscreem** [comment]
@addisonhall I think its still broken (for me anyway). I'm on version 0.1.0. Is there anything I can check in VS Code itself - just incase I'm being dumb and have set something up wrong?

**Comment by addisonhall** [comment]
Can you confirm that your language mode is set to "HTML (Statamic Antlers)"?

**Comment by sunscreem** [comment]
Hmm - I don't see that as an option:

![image](https://user-images.githubusercontent.com/7523595/102498332-b9f11a00-4071-11eb-8990-3642e4318301.png)


FYI - All seems to be installed correctly

![image](https://user-images.githubusercontent.com/7523595/102498512-fa509800-4071-11eb-9979-9c7e05d3b98b.png)


Only thing I have noticed is that this extensions is running locally and not my remote the same as more of the syntax/linters do?

**Comment by addisonhall** [comment]
Hmm... Something's definitely not right. Could you try disabling the extension, and then re-enable it for the workspace? Like so:

![Enable (Workspace)](https://github.com/addisonhall/ahdesign.antlers/blob/master/enable.gif?raw=true)

**Comment by sunscreem** [comment]
Thanks for you patience.

I've uninstalled it, re-installed it. It enabled it globally so I've disabled it then re-enabled it for workspace:

![image](https://user-images.githubusercontent.com/7523595/102504420-b7de8980-4078-11eb-9a45-59847550558b.png)

Still the same I'm afraid.

**Comment by addisonhall** [comment]
No worries, Rob. I'm afraid the only other thing I know to do is to try disabling any other "HTML" based templating languages like Liquid or Twig. And then, again, make sure Antlers is only enabled for your current workspace.

**Comment by addisonhall** [comment]
I've just found that my Twig extension kept Antlers from showing up in my languages list... maybe it's the same for you?

**Comment by sunscreem** [comment]
BOOM.

That's it! Disabled my (two?!) Twig extensions and its worked straight away with no changes needed.

**Comment by addisonhall** [comment]
Alright! Glad we figured that out! I'll go ahead and close this issue -- thanks, Rob.
