### ISSUE TITLE
Loop syntax highlighting not working

### ISSUE THREAD

**Issue by mattwaler** [addisonhall/ahdesign.antlers#6]
When using the loop syntax, the closing block highlighting does not work properly!

<img width="356" alt="Screen Shot 2020-10-12 at 9 10 52 PM" src="https://user-images.githubusercontent.com/32300026/95803970-7378eb00-0ccf-11eb-90fc-b51ed29d3177.png">

**Comment by addisonhall** [comment]
I'm not 100% sure, but it looks like you may have the Twig syntax active (see the little Twig icon to the left of default.antlers.html?). Can you confirm that Antlers is your current language mode?

**Comment by mattwaler** [comment]
This is super embarassing and you're totally right @addisonhall 🤯 

Will close and hide in my shame.

**Comment by addisonhall** [comment]
No worries at all!
