### ISSUE TITLE
Prettier / Format on save support?

### ISSUE THREAD

**Issue by kupe517** [addisonhall/ahdesign.antlers#8]
Is there any way to get formatting to work correctly? Given the following:
{{
    collection:press_releases
    :limit="total_limit"
    paginate="true"
    as="press_releases"
}}

(sorry can't use code formatting above since Github removes the line breaks)

becomes:
`{{ collection:press_releases :limit="total_limit" paginate="true" as="press_releases" }}`

when it is run through vscode formatter. I tried Beautify as well and the result is the same.

**Comment by addisonhall** [comment]
I would love to say I could do this, but I honestly don't know how :-P

I'm going to leave it open as an enhancement... Perhaps someone who know how will chip in. Thanks!

**Comment by iljapanic** [comment]
Anyone got prettier working with Antlers?

**Comment by addisonhall** [comment]
@iljapanic I highly recommend https://antlers.dev/. It should have long term support and it has WAY better features than mine.
